apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - namespace.yaml
  - ../../base
labels:
  - pairs:
      environment: production
    includeSelectors: false
patches:
  - path: deployment-prod.yaml
  - path: service-loadbalancer.yaml
configMapGenerator:
  - name: nestjs-backend-config
    literals:
      - APP_ENV=prod
      - GREETING_MESSAGE=Hello from NestJS in PRODUCTION on AKS
      - FEATURE_FLAGS=
      - LOG_LEVEL=log
      - STARTUP_DELAY_MS=0
      - DEMO_ENDPOINTS_ENABLED=false
